/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface User {
  createdAt: string;
  email: string;
  firstName: string;
  id: Generated<number>;
  lastName: string;
  passwordDigest: string;
  updatedAt: string;
}

export interface DB {
  users: User;
}
